#ifndef SETTINGS_DEFINES_H
#define SETTINGS_DEFINES_H

#define CONFIG_DELIMITER				"="

#define SETTINGS_COUNT					12

#define SETTING_POLLING_TIME				0
#define SETTING_MODBUS_ADDRESS				1
#define SETTING_MODBUS_PORT				2
#define SETTING_MODBUS_REGISTER				3
#define SETTING_MODBUS_REGISTER_TYPE			4
#define SETTING_MODBUS_DESIRED_BIT			5
#define SETTING_MODBUS_DATA_TYPE			6
#define SETTING_MOSQUITTO_ADDRESS			7
#define SETTING_MOSQUITTO_PORT				8
#define SETTING_MOSQUITTO_USER				9
#define SETTING_MOSQUITTO_PASSWORD			10
#define SETTING_MOSQUITTO_TOPIC				11

#endif